version: "3.1"

services:
  application:
    image: application
    build:
      context: ./application
      dockerfile: Dockerfile
    depends_on:
      worker-a:
        condition: service_started
      worker-b:
        condition: service_started

  worker-a:
    image: worker-type-a
    build:
      context: ./worker_type_a
      dockerfile: Dockerfile
    deploy:
      replicas: 10

  worker-b:
    image: worker-type-b
    build:
      context: ./worker_type_b
      dockerfile: Dockerfile
    deploy:
      replicas: 1

  flower:
    image: mher/flower:0.9.7
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@rabbitmq
      - FLOWER_PORT=8888
    ports:
      - "8889:8888"
